x <- 3.663422242
y <- 3.343545435
z <- -3.66736728
w <- -3.46767666
cat("#Ceiling==> Rounds to nearest integer greater than x or y\n")  
ceiling(x)
ceiling(y)
ceiling(z)
ceiling(w)
cat("#Floor==> Rounds to nearest integer smaller than x or y\n")
floor(x)
floor(y)
floor(w)
floor(z) 
cat("#Round\n")
round(x,2)
round(x)
round(y,3)
round(y)
round(w,1)
round(w)
round(z,3)
round(z)
cat("#Trunc\n")
trunc(x)
trunc(y)
trunc(z)
trunc(w)
# Observe the outputs of trunc, round, floor and understand the differences among them 

#Applying precison functions on matrix
cat("#Creation of matrices using random values\n")
x <- runif(20,40,60)
y <- runif(20,45,55)
x.mat <- matrix(x,ncol=4,nrow=5)
y.mat <- matrix(y,ncol=4,nrow=5)
x.mat
y.mat
cat("#ceiling\n")
ceiling(x.mat)
ceiling(y.mat)
ceiling(x.mat*y.mat)
cat("#floor\n")
floor(x.mat)
floor(y.mat)
floor(x.mat%%y.mat)
cat("#round\n")
round(x.mat)
round(y.mat)
round(x.mat/y.mat,2)
cat("#trunc\n")
trunc(x.mat)
trunc(y.mat)
trunc(x.mat%/%y.mat)